apiVersion: v1
kind: Service
metadata:
  name: kubernetes-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    k8s-app: api-server
  ports:
    - protocol: TCP
      port: 6443
      targetPort: 6443
