apiVersion: v1
kind: Service
metadata:
  name: k3s-api-server
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6443
      targetPort: 6443
  selector:
    app: kubernetes