apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
      - name: chronograf
        image: chronograf:latest
        ports:
        - containerPort: 8888
        env:
        - name: INFLUXDB_URL
          value: "http://influxdb:8086"
        - name: INFLUXDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: influxdb-auth
              key: admin-username
        - name: INFLUXDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-auth
              key: admin-password
---
apiVersion: v1
kind: Service
metadata:
  name: chronograf
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: chronograf
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app.kubernetes.io/name: influxdb