apiVersion: v1
kind: Service
metadata:
  name: influxdb-lb
  namespace: $NAMESPACE
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8086
  selector:
    app.kubernetes.io/name: influxdb