apiVersion: v1
kind: Service
metadata:
  name: k3s-api-server
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: k3s-api
    metallb.universe.tf/loadBalancerIPs: 192.168.1.240  
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6443
      targetPort: 6443
  selector:
    component: kube-apiserver 