controller:
  kind: DaemonSet
  hostNetwork: false
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  publishService:
    enabled: true
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.241  # Choose an available IP from your MetalLB range
  metrics:
    enabled: true