global:
  storageClass: "local-storage"

zookeeper:
  enabled: true
  replicaCount: 3
  persistence:
    size: 1Gi

kafka:
  replicaCount: 3
  persistence:
    size: 5Gi
  externalAccess:
    enabled: false  # Set to true if you need external access
  brokers:
    - id: 0
      host: kafka-0
    - id: 1
      host: kafka-1
    - id: 2
      host: kafka-2

controller:
  enabled: false  # Explicitly disable controller for Zookeeper mode
  replicaCount: 0

metrics:
  kafka:
    enabled: true
  zookeeper:
    enabled: true

serviceAccount:
  create: true

migration:
  enabled: false  # We're not migrating to KRaft
  mode: "none"

# Ensure KRaft mode is disabled
kraft:
  enabled: false