global:
  storageClass: "local-storage"

zookeeper:
  enabled: true
  replicaCount: 3
  persistence:
    size: 1Gi

replicaCount: 3
architecture: "kraft"

persistence:
  size: 5Gi

externalAccess:
  enabled: false

metrics:
  kafka:
    enabled: true
  zookeeper:
    enabled: true

serviceAccount:
  create: true

# Explicitly disable KRaft mode
kraft:
  enabled: false