global:
  storageClass: "local-storage"

zookeeper:
  enabled: true
  replicaCount: 3
  persistence:
    size: 1Gi

# Kafka broker configuration
replicaCount: 3
persistence:
  size: 5Gi

# Explicitly configure Kafka brokers
broker:
  replicaCount: 3

# Disable controller for Zookeeper mode
controller:
  replicaCount: 0

# Disable KRaft mode
kraft:
  enabled: false

externalAccess:
  enabled: false

metrics:
  kafka:
    enabled: true
  zookeeper:
    enabled: true

serviceAccount:
  create: true

# Ensure we're not in migration mode
migration:
  enabled: false