---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-client-config
  namespace: kafka
data:
  client.properties: |
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=SCRAM-SHA-256
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
        username="user1" \
        password="${KAFKA_PASSWORD}";
  produce-messages.sh: |
    #!/bin/bash
    while true; do
      echo "Producing message at $(date)"
      echo "Test message at $(date)" | kafka-console-producer.sh \
        --producer.config /tmp/client.properties \
        --broker-list kafka-broker-0.kafka-broker-headless.kafka.svc.cluster.local:9092,kafka-broker-1.kafka-broker-headless.kafka.svc.cluster.local:9092,kafka-broker-2.kafka-broker-headless.kafka.svc.cluster.local:9092 \
        --topic test
      sleep 5
    done
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-producer
  namespace: kafka
spec:
  containers:
  - name: kafka-test-producer
    image: docker.io/bitnami/kafka:3.7.1-debian-12-r4
    command: ["/bin/bash", "-c"]
    args:
    - |
      export KAFKA_PASSWORD=$(cat /tmp/kafka-password)
      sed "s/\${KAFKA_PASSWORD}/$KAFKA_PASSWORD/" /etc/kafka/client.properties > /tmp/client.properties
      cp /etc/kafka/produce-messages.sh /tmp/produce-messages.sh
      chmod +x /tmp/produce-messages.sh
      /tmp/produce-messages.sh
    volumeMounts:
    - name: config
      mountPath: /etc/kafka
    - name: kafka-password
      mountPath: /tmp/kafka-password
      subPath: kafka-password
  volumes:
  - name: config
    configMap:
      name: kafka-client-config
  - name: kafka-password
    secret:
      secretName: kafka-user-passwords
      items:
      - key: client-passwords
        path: kafka-password