global:
  storageClass: "longhorn-storage"

zookeeper:
  enabled: true
  replicaCount: 3
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Kafka broker configuration
replicaCount: 3
persistence:
  size: 5Gi

# Explicitly configure Kafka brokers
broker:
  replicaCount: 3
  resources:
    requests:
      cpu: "250m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

# Disable controller for Zookeeper mode
controller:
  replicaCount: 0

# Disable KRaft mode
kraft:
  enabled: false

externalAccess:
  enabled: false

metrics:
  kafka:
    enabled: true
  zookeeper:
    enabled: true

serviceAccount:
  create: true

# Ensure we're not in migration mode
migration:
  enabled: false

auth:
  clientProtocol: sasl
  interBrokerProtocol: sasl
  sasl:
    mechanisms: plain
    interBrokerMechanism: plain
  # Add the following for better security:
  tls:
    enabled: true
    autoGenerated: true

# Monitoring
prometheusRule:
  enabled: true

# Add the following for better monitoring
serviceMonitor:
  enabled: true

# Add the following for auto-creating topics
autoCreateTopicsEnable: true

# Logging
logPersistence:
  enabled: true
  size: 2Gi

# Readiness and liveness probes
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

extraConfig: |
  log.retention.hours=168
  log.retention.bytes=1073741824