global:
  storageClass: "local-storage"

replicaCount: 3

externalAccess:
  enabled: false  # Changed to false

persistence:
  size: 5Gi

zookeeper:
  enabled: true
  replicaCount: 2
  persistence:
    size: 1Gi

kraft:
  enabled: false  # Explicitly disable KRaft mode

controller:
  replicaCount: 2  # Set to 2 as we're using Zookeeper mode

metrics:
  kafka:
    enabled: true
  zookeeper:
    enabled: true

serviceAccount:
  create: true